// Full 22-category course catalog with starter content

export interface CategoryTrack {
  id: string;
  name: string;
  icon: string;
  description: string;
  levels: { level: string; modules: string[] }[];
  starterLessons: { title: string; hook: string; difficulty: string }[];
  workflows: { title: string; steps: string[] }[];
  prompts: { label: string; prompt: string; level: "beginner" | "pro" }[];
  scenario: { title: string; description: string };
}

export const CATEGORY_TRACKS: CategoryTrack[] = [
  {
    id: "management", name: "Management", icon: "👔", description: "Lead teams, delegate tasks, and make decisions with AI assistance.",
    levels: [
      { level: "Beginner", modules: ["What AI Can Do for Managers", "Meeting Automation", "Team Communication", "Decision Frameworks"] },
      { level: "Intermediate", modules: ["Performance Reviews with AI", "Strategic Planning", "Conflict Resolution", "Change Management"] },
      { level: "Advanced", modules: ["AI-Driven Leadership", "Organizational Design", "Executive Communication", "Crisis Management"] },
    ],
    starterLessons: [
      { title: "AI Meeting Summarizer", hook: "Turn 1-hour meetings into 2-minute summaries.", difficulty: "beginner" },
      { title: "Decision Matrix with AI", hook: "Make better decisions in 60 seconds.", difficulty: "beginner" },
      { title: "Performance Review Generator", hook: "Write fair, specific reviews 5x faster.", difficulty: "intermediate" },
      { title: "Team Capacity Planner", hook: "Balance workloads using AI analysis.", difficulty: "intermediate" },
      { title: "Delegation Framework", hook: "Know what to delegate and how to brief it.", difficulty: "beginner" },
      { title: "1-on-1 Meeting Prep", hook: "AI-generated talking points for every report.", difficulty: "beginner" },
      { title: "Strategic OKR Builder", hook: "Create aligned objectives in minutes.", difficulty: "intermediate" },
      { title: "Conflict Script Generator", hook: "Navigate tough conversations with a script.", difficulty: "advanced" },
      { title: "Change Communication Plan", hook: "Roll out changes with clear messaging.", difficulty: "advanced" },
      { title: "Leadership Style Analyzer", hook: "Understand and adapt your management approach.", difficulty: "intermediate" },
    ],
    workflows: [
      { title: "Weekly Team Review", steps: ["Collect status updates", "AI summarize progress", "Identify blockers", "Generate action items", "Send team digest"] },
      { title: "Hiring Decision Framework", steps: ["Define role requirements", "Score candidates with rubric", "AI analyze comparison", "Team discussion points", "Final decision matrix"] },
      { title: "Project Kickoff", steps: ["Define scope with AI", "Generate timeline", "Assign responsibilities", "Create communication plan", "Set milestones"] },
      { title: "Quarterly Planning", steps: ["Review past quarter metrics", "AI identify trends", "Set new objectives", "Resource allocation", "Stakeholder presentation"] },
      { title: "Crisis Response", steps: ["Assess situation", "AI draft communications", "Assign response team", "Monitor progress", "Post-mortem analysis"] },
    ],
    prompts: [
      { label: "Meeting Summary", prompt: "Summarize this meeting transcript into: Key Decisions, Action Items (with owners), Open Questions, Next Steps.", level: "beginner" },
      { label: "Performance Feedback", prompt: "Write constructive feedback for an employee who [situation]. Use the SBI framework (Situation, Behavior, Impact).", level: "beginner" },
      { label: "Strategic Memo", prompt: "Draft a strategic memo proposing [initiative]. Include: problem statement, proposed solution, resource requirements, timeline, risk mitigation, expected ROI.", level: "pro" },
      { label: "Team Restructure Plan", prompt: "Analyze this team structure and suggest optimization for [goal]. Consider: skill gaps, workload balance, career growth, collaboration patterns.", level: "pro" },
      { label: "Stakeholder Update", prompt: "Write a concise executive update on [project]. Format: Status (green/yellow/red), Key Wins, Risks, Asks, Timeline.", level: "beginner" },
      { label: "Interview Questions", prompt: "Generate 10 behavioral interview questions for a [role]. Focus on: problem-solving, collaboration, adaptability. Include what to look for in answers.", level: "beginner" },
      { label: "Retention Strategy", prompt: "Analyze potential causes of employee turnover in [department] and suggest 5 actionable retention strategies with estimated impact.", level: "pro" },
      { label: "Budget Justification", prompt: "Write a budget justification for [request]. Include: business case, alternatives considered, ROI timeline, risk of not investing.", level: "pro" },
      { label: "Delegation Brief", prompt: "Create a delegation brief for [task]: context, expected output, constraints, checkpoints, success criteria.", level: "beginner" },
      { label: "Vision Statement", prompt: "Craft a compelling team vision statement that aligns with [company mission]. Make it memorable, actionable, and inspiring.", level: "pro" },
    ],
    scenario: { title: "Managing a Remote Team Crisis", description: "Your remote team misses a critical deadline. Use AI to analyze the situation, draft communications to stakeholders, create a recovery plan, and prevent future issues." },
  },
  {
    id: "business-finance", name: "Business & Finance", icon: "💰", description: "Financial analysis, budgeting, and business strategy with AI.",
    levels: [
      { level: "Beginner", modules: ["Budget Basics with AI", "Invoice Templates", "Financial Terminology", "Cash Flow Tracking"] },
      { level: "Intermediate", modules: ["Financial Modeling", "Investment Analysis", "Tax Planning", "Business Valuation"] },
      { level: "Advanced", modules: ["M&A Analysis", "Portfolio Strategy", "Risk Management", "Financial Forecasting"] },
    ],
    starterLessons: [
      { title: "Cash Flow Forecaster", hook: "Predict your finances 90 days ahead.", difficulty: "beginner" },
      { title: "Invoice Template Builder", hook: "Professional invoices in 30 seconds.", difficulty: "beginner" },
      { title: "Expense Category Optimizer", hook: "Find savings you didn't know existed.", difficulty: "beginner" },
      { title: "Break-Even Calculator", hook: "Know exactly when your project pays off.", difficulty: "intermediate" },
      { title: "Competitive Pricing Analysis", hook: "Price products using market data.", difficulty: "intermediate" },
      { title: "Financial KPI Dashboard", hook: "Track the numbers that actually matter.", difficulty: "intermediate" },
      { title: "ROI Calculator Template", hook: "Justify any investment with data.", difficulty: "beginner" },
      { title: "Subscription Revenue Modeler", hook: "Model MRR growth scenarios.", difficulty: "advanced" },
      { title: "Tax Deduction Finder", hook: "Identify deductions you might be missing.", difficulty: "beginner" },
      { title: "Investor Pitch Financials", hook: "Build financial slides investors want to see.", difficulty: "advanced" },
    ],
    workflows: [
      { title: "Monthly Financial Review", steps: ["Export bank data", "AI categorize expenses", "Compare to budget", "Identify anomalies", "Generate report"] },
      { title: "Pricing Strategy", steps: ["Research competitor pricing", "Calculate costs", "AI analyze price sensitivity", "Set price tiers", "A/B test messaging"] },
      { title: "Business Plan Draft", steps: ["Define value proposition", "Market size analysis", "Financial projections", "Risk assessment", "Executive summary"] },
      { title: "Fundraising Prep", steps: ["Financial model cleanup", "AI generate pitch deck", "Prepare Q&A responses", "Due diligence checklist", "Investor outreach plan"] },
      { title: "Cost Reduction Audit", steps: ["List all expenses", "AI categorize by necessity", "Identify alternatives", "Calculate savings", "Implementation timeline"] },
    ],
    prompts: [
      { label: "Budget Template", prompt: "Create a monthly business budget for a [type] business with $[X] revenue. Categorize: fixed costs, variable costs, discretionary.", level: "beginner" },
      { label: "Financial Report", prompt: "Analyze these financial numbers and generate a report: Revenue, Expenses, Profit margin, YoY growth, Key concerns.", level: "pro" },
      { label: "Cash Flow Projection", prompt: "Create a 12-month cash flow projection for [business]. Include: seasonal adjustments, growth assumptions, buffer recommendations.", level: "pro" },
      { label: "Expense Analysis", prompt: "Categorize these expenses and identify top 3 areas for cost reduction with estimated savings.", level: "beginner" },
      { label: "Investment Comparison", prompt: "Compare these investment options: [list]. Analyze: risk level, expected return, liquidity, time horizon, tax implications.", level: "pro" },
      { label: "Pricing Calculator", prompt: "Calculate optimal pricing for [product/service]. Inputs: cost, market rate, value delivered, competitor prices.", level: "beginner" },
      { label: "Revenue Model", prompt: "Build a revenue model for [business type] with 3 scenarios: conservative, moderate, aggressive. Include key assumptions.", level: "pro" },
      { label: "Financial Health Check", prompt: "Evaluate this business's financial health using: current ratio, debt-to-equity, profit margin, burn rate.", level: "pro" },
      { label: "Tax Planning", prompt: "List common tax deductions for [business type]. Categorize by: easy to claim, requires documentation, consult accountant.", level: "beginner" },
      { label: "Unit Economics", prompt: "Calculate unit economics for [product]: CAC, LTV, payback period, gross margin per unit.", level: "pro" },
    ],
    scenario: { title: "Launching a Side Business", description: "You're starting a freelance consulting business. Use AI to create a business plan, set pricing, build a budget, forecast 6 months of cash flow, and identify potential risks." },
  },
  {
    id: "computer-math", name: "Computer & Math", icon: "💻", description: "Programming, data analysis, and computational thinking with AI.",
    levels: [
      { level: "Beginner", modules: ["Code Explanation", "Debugging with AI", "Data Basics", "Spreadsheet Formulas"] },
      { level: "Intermediate", modules: ["Algorithm Design", "Database Queries", "API Integration", "Data Visualization"] },
      { level: "Advanced", modules: ["System Architecture", "ML Concepts", "Performance Optimization", "Security Practices"] },
    ],
    starterLessons: [
      { title: "Debug Like a Pro", hook: "AI finds bugs faster than you think.", difficulty: "beginner" },
      { title: "Regex Made Simple", hook: "Pattern matching explained in plain English.", difficulty: "intermediate" },
      { title: "SQL Query Builder", hook: "Write database queries without memorizing syntax.", difficulty: "beginner" },
      { title: "API Explained Simply", hook: "APIs are just restaurant waiters for data.", difficulty: "beginner" },
      { title: "Spreadsheet Formula Wizard", hook: "Complex formulas written by AI.", difficulty: "beginner" },
      { title: "Data Cleaning Pipeline", hook: "Turn messy data into clean datasets.", difficulty: "intermediate" },
      { title: "Code Review Checklist", hook: "AI reviews your code like a senior dev.", difficulty: "intermediate" },
      { title: "Algorithm Selection Guide", hook: "Pick the right algorithm for any problem.", difficulty: "advanced" },
      { title: "Git Workflow for Humans", hook: "Version control without the headaches.", difficulty: "beginner" },
      { title: "Statistics for Decisions", hook: "Use basic stats to make better choices.", difficulty: "intermediate" },
    ],
    workflows: [
      { title: "Code Review Pipeline", steps: ["Submit code to AI", "Check for bugs", "Optimize performance", "Review security", "Generate documentation"] },
      { title: "Data Analysis Sprint", steps: ["Define question", "Clean data with AI", "Analyze patterns", "Visualize findings", "Write summary"] },
      { title: "Learning New Language", steps: ["AI compare to known language", "Key syntax differences", "Build small project", "Debug with AI", "Refactor for best practices"] },
      { title: "Spreadsheet Automation", steps: ["Identify repetitive tasks", "AI generate formulas", "Create macros", "Test with sample data", "Document process"] },
      { title: "Bug Investigation", steps: ["Describe symptoms", "AI suggest causes", "Test hypotheses", "Apply fix", "Add regression test"] },
    ],
    prompts: [
      { label: "Code Explainer", prompt: "Explain this code line by line as if I'm a beginner. Highlight key concepts and potential issues.", level: "beginner" },
      { label: "Debug Helper", prompt: "I'm getting this error: [error]. Here's my code: [code]. Find the bug, explain why it happens, and show the fix.", level: "beginner" },
      { label: "SQL Generator", prompt: "Write a SQL query to: [description]. Table structure: [tables]. Include comments explaining each part.", level: "beginner" },
      { label: "Architecture Review", prompt: "Review this system architecture for: scalability, security, maintainability, cost. Suggest improvements.", level: "pro" },
      { label: "Regex Builder", prompt: "Create a regex pattern to match: [description]. Explain each part of the pattern. Include test cases.", level: "pro" },
      { label: "Excel Formula", prompt: "Write an Excel/Sheets formula to: [task]. Explain the formula components.", level: "beginner" },
      { label: "API Documentation", prompt: "Generate API documentation for this endpoint: [details]. Include: description, parameters, response format, error codes, examples.", level: "pro" },
      { label: "Performance Optimizer", prompt: "Analyze this code for performance bottlenecks. Suggest optimizations with expected improvement.", level: "pro" },
      { label: "Data Model Design", prompt: "Design a database schema for [application]. Include: tables, relationships, indexes, constraints.", level: "pro" },
      { label: "Algorithm Picker", prompt: "I need to solve [problem]. Suggest the best algorithm, explain time/space complexity, and provide pseudocode.", level: "pro" },
    ],
    scenario: { title: "Building a Data Dashboard", description: "Your boss needs a sales dashboard. Use AI to write SQL queries, create spreadsheet formulas, build data visualizations, and automate weekly reporting." },
  },
  {
    id: "architecture", name: "Architecture & Engineering", icon: "🏗️", description: "Design, planning, and engineering problem-solving with AI.",
    levels: [
      { level: "Beginner", modules: ["Design Brief Writing", "Material Research", "Code Compliance Basics", "Project Documentation"] },
      { level: "Intermediate", modules: ["Structural Calculations", "Energy Modeling", "BIM Workflows", "Cost Estimation"] },
      { level: "Advanced", modules: ["Parametric Design", "Sustainability Analysis", "Complex Systems", "Innovation Research"] },
    ],
    starterLessons: [
      { title: "Design Brief Generator", hook: "Create clear project briefs in minutes.", difficulty: "beginner" },
      { title: "Material Comparison Matrix", hook: "Compare materials across 10 dimensions.", difficulty: "intermediate" },
      { title: "Code Compliance Checker", hook: "Quick-reference building codes with AI.", difficulty: "beginner" },
      { title: "Cost Estimation Template", hook: "Ballpark project costs accurately.", difficulty: "intermediate" },
      { title: "Site Analysis Report", hook: "AI-assisted site survey documentation.", difficulty: "beginner" },
      { title: "Sustainability Scorecard", hook: "Rate designs on environmental impact.", difficulty: "intermediate" },
      { title: "RFP Response Writer", hook: "Win more projects with better proposals.", difficulty: "advanced" },
      { title: "Punch List Generator", hook: "Never miss a detail at handoff.", difficulty: "beginner" },
      { title: "Specification Writer", hook: "Technical specs without the tedium.", difficulty: "intermediate" },
      { title: "Value Engineering Guide", hook: "Cut costs without cutting quality.", difficulty: "advanced" },
    ],
    workflows: [
      { title: "Project Feasibility Study", steps: ["Define requirements", "AI research regulations", "Cost-benefit analysis", "Risk assessment", "Recommendation report"] },
      { title: "Design Review", steps: ["Compile design documents", "AI check compliance", "Identify issues", "Suggest alternatives", "Document decisions"] },
      { title: "Material Selection", steps: ["List requirements", "AI compare options", "Cost analysis", "Sustainability check", "Final specification"] },
      { title: "Construction Documentation", steps: ["Draft specifications", "AI review for gaps", "Cross-reference codes", "Format deliverables", "Quality check"] },
      { title: "Post-Occupancy Evaluation", steps: ["Survey occupants", "AI analyze feedback", "Performance metrics", "Improvement recommendations", "Implementation plan"] },
    ],
    prompts: [
      { label: "Design Brief", prompt: "Create a design brief for [project type]. Include: objectives, constraints, user needs, budget range, timeline, sustainability goals.", level: "beginner" },
      { label: "Material Research", prompt: "Compare [material A] vs [material B] for [application]. Evaluate: durability, cost, sustainability, aesthetics, maintenance.", level: "beginner" },
      { label: "RFP Response", prompt: "Draft an RFP response for [project]. Highlight: relevant experience, approach, team qualifications, timeline, value proposition.", level: "pro" },
      { label: "Code Review", prompt: "Check if [design element] meets [building code/standard]. Flag potential issues and suggest compliant alternatives.", level: "pro" },
      { label: "Site Report", prompt: "Generate a site analysis report template for [location type]. Include: topography, access, utilities, environmental factors, zoning.", level: "beginner" },
      { label: "Energy Analysis", prompt: "Estimate energy performance for [building type] with [features]. Suggest improvements for LEED/BREEAM certification.", level: "pro" },
      { label: "Cost Estimate", prompt: "Create a preliminary cost estimate for [project]. Break down by: structure, MEP, finishes, site work, contingency.", level: "beginner" },
      { label: "Spec Writer", prompt: "Write a specification section for [element]. Include: scope, materials, execution, quality assurance, submittals.", level: "pro" },
      { label: "Sustainability Plan", prompt: "Develop a sustainability strategy for [project]. Cover: energy, water, materials, waste, indoor quality, site ecology.", level: "pro" },
      { label: "Punch List", prompt: "Generate a comprehensive punch list template for [project phase]. Organize by: location, trade, priority, responsible party.", level: "beginner" },
    ],
    scenario: { title: "Renovating a Historic Building", description: "You're tasked with modernizing a 100-year-old building while preserving its character. Use AI to research code requirements, compare materials, estimate costs, and create a phased renovation plan." },
  },
  {
    id: "life-sciences", name: "Life & Social Sciences", icon: "🔬", description: "Research methods, analysis, and scientific communication with AI.",
    levels: [
      { level: "Beginner", modules: ["Literature Review Basics", "Research Question Framing", "Data Collection", "Report Writing"] },
      { level: "Intermediate", modules: ["Statistical Analysis", "Survey Design", "Qualitative Coding", "Grant Writing"] },
      { level: "Advanced", modules: ["Meta-Analysis", "Publication Strategy", "Research Ethics", "Policy Briefs"] },
    ],
    starterLessons: [
      { title: "Literature Review Helper", hook: "Organize research papers in minutes.", difficulty: "beginner" },
      { title: "Research Question Builder", hook: "Frame better research questions.", difficulty: "beginner" },
      { title: "Survey Design Checklist", hook: "Avoid the 7 most common survey mistakes.", difficulty: "intermediate" },
      { title: "Stats Interpreter", hook: "Understand p-values without a PhD.", difficulty: "beginner" },
      { title: "Abstract Writer", hook: "Structured abstracts in 2 minutes.", difficulty: "intermediate" },
      { title: "Citation Formatter", hook: "Never format citations manually again.", difficulty: "beginner" },
      { title: "Grant Proposal Outline", hook: "Structure winning proposals.", difficulty: "advanced" },
      { title: "Data Visualization Picker", hook: "Choose the right chart every time.", difficulty: "beginner" },
      { title: "Interview Guide Builder", hook: "Create semi-structured interview guides.", difficulty: "intermediate" },
      { title: "Findings Communicator", hook: "Translate research for non-experts.", difficulty: "intermediate" },
    ],
    workflows: [
      { title: "Literature Review Pipeline", steps: ["Define search terms", "AI screen abstracts", "Extract key findings", "Identify gaps", "Write synthesis"] },
      { title: "Survey Research", steps: ["Define objectives", "AI draft questions", "Pilot test", "Analyze responses", "Report findings"] },
      { title: "Data Analysis", steps: ["Clean dataset", "Descriptive statistics", "AI suggest tests", "Run analysis", "Interpret results"] },
      { title: "Grant Application", steps: ["Research funding sources", "Draft proposal", "AI review and refine", "Budget justification", "Submit package"] },
      { title: "Publication Prep", steps: ["Select target journal", "Format per guidelines", "AI review manuscript", "Draft cover letter", "Submit and track"] },
    ],
    prompts: [
      { label: "Research Question", prompt: "Help me refine this research question: [draft]. Make it specific, measurable, and researchable. Suggest 2-3 alternatives.", level: "beginner" },
      { label: "Literature Summary", prompt: "Summarize this research paper: [abstract/intro]. Extract: main finding, methodology, limitations, implications.", level: "beginner" },
      { label: "Stats Explainer", prompt: "Explain this statistical result in plain English: [result]. What does it mean practically?", level: "beginner" },
      { label: "Grant Narrative", prompt: "Write a grant proposal narrative for: [project]. Include: significance, innovation, approach, timeline, expected outcomes.", level: "pro" },
      { label: "Methods Section", prompt: "Draft a methods section for: [study design]. Include: participants, measures, procedure, analysis plan.", level: "pro" },
      { label: "Survey Questions", prompt: "Generate 15 survey questions about [topic]. Include: Likert scale, multiple choice, and open-ended. Avoid leading questions.", level: "beginner" },
      { label: "Data Dictionary", prompt: "Create a data dictionary for [dataset]. Include: variable name, type, description, valid values, missing data codes.", level: "pro" },
      { label: "Abstract Writer", prompt: "Write a structured abstract (Background, Methods, Results, Conclusion) for: [study summary]. Max 250 words.", level: "pro" },
      { label: "Ethics Application", prompt: "Draft an ethics application for [research]. Cover: informed consent, risks, benefits, data protection, vulnerable populations.", level: "pro" },
      { label: "Plain Language Summary", prompt: "Translate this research finding into a plain language summary for the general public. Max 100 words.", level: "beginner" },
    ],
    scenario: { title: "Conducting a Community Survey", description: "You need to survey 500 community members about local services. Use AI to design the survey, plan sampling, analyze mock results, and write a findings report." },
  },
  // Remaining categories with compact format
  ...[
    { id: "social-services", name: "Social Services", icon: "🤝", desc: "Case management, community resources, and client support with AI." },
    { id: "legal", name: "Legal", icon: "⚖️", desc: "Legal research, document drafting, and compliance with AI." },
    { id: "education", name: "Education & Library", icon: "📚", desc: "Curriculum design, lesson planning, and information literacy with AI." },
    { id: "arts-media", name: "Arts & Media", icon: "🎨", desc: "Creative production, content strategy, and media management with AI." },
    { id: "healthcare-pract", name: "Healthcare Practitioners", icon: "⚕️", desc: "Clinical documentation, research, and patient communication with AI." },
    { id: "healthcare-support", name: "Healthcare Support", icon: "🏥", desc: "Patient care documentation, scheduling, and protocols with AI." },
    { id: "protective", name: "Protective Service", icon: "🛡️", desc: "Safety protocols, report writing, and risk assessment with AI." },
    { id: "food-serving", name: "Food & Serving", icon: "🍽️", desc: "Menu planning, inventory, and customer service with AI." },
    { id: "grounds", name: "Grounds Maintenance", icon: "🌿", desc: "Landscape planning, scheduling, and equipment management with AI." },
    { id: "personal-care", name: "Personal Care", icon: "💆", desc: "Client management, scheduling, and service planning with AI." },
    { id: "sales", name: "Sales", icon: "📊", desc: "Prospecting, pitching, and closing deals with AI." },
    { id: "office-admin", name: "Office & Admin", icon: "📋", desc: "Document management, scheduling, and process automation with AI." },
    { id: "agriculture", name: "Agriculture", icon: "🌾", desc: "Crop planning, market analysis, and farm management with AI." },
    { id: "construction", name: "Construction", icon: "🔨", desc: "Project management, safety, and estimation with AI." },
    { id: "installation", name: "Installation & Repair", icon: "🔧", desc: "Troubleshooting, documentation, and customer service with AI." },
    { id: "production", name: "Production", icon: "🏭", desc: "Quality control, process optimization, and inventory with AI." },
    { id: "transportation", name: "Transportation", icon: "🚛", desc: "Route optimization, logistics, and compliance with AI." },
  ].map(cat => ({
    id: cat.id, name: cat.name, icon: cat.icon, description: cat.desc,
    levels: [
      { level: "Beginner", modules: [`${cat.name} AI Basics`, "Documentation with AI", "Communication Templates", "Daily Task Automation"] },
      { level: "Intermediate", modules: ["Process Optimization", "Data Analysis", "Client/Stakeholder Management", "Quality Systems"] },
      { level: "Advanced", modules: ["Strategic Planning", "Innovation & Trends", "Leadership Applications", "Industry Specialization"] },
    ],
    starterLessons: [
      { title: `AI for ${cat.name} Intro`, hook: `Discover how AI transforms ${cat.name.toLowerCase()}.`, difficulty: "beginner" },
      { title: "Report Writing with AI", hook: "Professional reports in half the time.", difficulty: "beginner" },
      { title: "Email Templates", hook: "Handle any message in 30 seconds.", difficulty: "beginner" },
      { title: "Task Prioritization", hook: "AI helps you focus on what matters.", difficulty: "beginner" },
      { title: "Client Communication", hook: "Say the right thing every time.", difficulty: "intermediate" },
      { title: "Process Documentation", hook: "Turn know-how into repeatable SOPs.", difficulty: "intermediate" },
      { title: "Problem-Solving Framework", hook: "Structured troubleshooting with AI.", difficulty: "intermediate" },
      { title: "Industry Trends Scanner", hook: "Stay ahead of changes in your field.", difficulty: "intermediate" },
      { title: "Safety Checklist Builder", hook: "Never miss a safety requirement.", difficulty: "beginner" },
      { title: "Professional Development Plan", hook: "Map your career growth with AI.", difficulty: "advanced" },
    ],
    workflows: [
      { title: "Daily Planning", steps: ["Review tasks", "AI prioritize", "Time block", "Set goals", "End-of-day review"] },
      { title: "Documentation System", steps: ["Template creation", "AI fill details", "Review & edit", "Distribute", "Update tracking"] },
      { title: "Client Interaction", steps: ["Prep with AI", "Meeting notes", "Follow-up draft", "Task extraction", "CRM update"] },
      { title: "Quality Assurance", steps: ["Define standards", "AI checklist", "Inspection", "Report findings", "Improvement plan"] },
      { title: "Training New Staff", steps: ["Create guide", "AI quiz generator", "Practice scenarios", "Assessment", "Feedback loop"] },
    ],
    prompts: [
      { label: "Daily Report", prompt: `Write a daily ${cat.name.toLowerCase()} report covering: completed tasks, issues encountered, tomorrow's priorities.`, level: "beginner" as const },
      { label: "Client Email", prompt: "Draft a professional email to [client] about [topic]. Tone: helpful and clear. Include next steps.", level: "beginner" as const },
      { label: "Process SOP", prompt: `Create a Standard Operating Procedure for [task] in ${cat.name.toLowerCase()}. Include: purpose, steps, safety notes, quality checks.`, level: "beginner" as const },
      { label: "Problem Analysis", prompt: "Analyze this issue: [description]. Identify: root cause, immediate actions, long-term fix, prevention.", level: "pro" as const },
      { label: "Training Material", prompt: `Create training material for new ${cat.name.toLowerCase()} staff on [topic]. Include: key concepts, common mistakes, practice exercises.`, level: "beginner" as const },
      { label: "Cost Estimate", prompt: "Estimate costs for [project/task]. Break down: labor, materials, equipment, overhead, contingency.", level: "pro" as const },
      { label: "Safety Protocol", prompt: `Write a safety protocol for [activity] in ${cat.name.toLowerCase()}. Include: hazards, PPE, procedures, emergency contacts.`, level: "beginner" as const },
      { label: "Performance Metrics", prompt: "Define KPIs for [role/process]. Include: metric name, target, measurement method, frequency.", level: "pro" as const },
      { label: "Improvement Proposal", prompt: "Write a process improvement proposal for [current process]. Include: current state, proposed changes, expected benefits, implementation plan.", level: "pro" as const },
      { label: "Industry Update", prompt: `Summarize recent trends in ${cat.name.toLowerCase()} that could affect our operations. Include: opportunities, threats, recommended actions.`, level: "pro" as const },
    ],
    scenario: { title: `A Day in ${cat.name}`, description: `Simulate a challenging day in ${cat.name.toLowerCase()}. Handle client requests, solve unexpected problems, write reports, and optimize your workflow using AI at every step.` },
  })),
];

export function getCategoryTrack(id: string): CategoryTrack | undefined {
  return CATEGORY_TRACKS.find(t => t.id === id);
}
