// Wisdom AI — Core data

export const QUOTES = [
  "The best way to predict the future is to create it with intelligence.",
  "AI doesn't replace thinking — it amplifies it.",
  "A well-crafted prompt is worth a thousand searches.",
  "Mastery isn't about knowing everything. It's about knowing what to ask.",
  "The gap between you and AI mastery is one lesson a day.",
  "Intelligence is not fixed. It compounds with every question you ask.",
  "Verify everything. Trust nothing blindly. That's real AI literacy.",
  "The future belongs to those who learn to collaborate with machines.",
  "Your prompts are your superpower. Sharpen them daily.",
  "Every expert was once a beginner who refused to stop learning.",
  "The quality of your AI output is the quality of your input.",
  "Don't just use AI — understand it. That's the real advantage.",
  "Clarity of thought produces clarity of output.",
  "The most dangerous AI myth: that it's always right.",
  "Automate the boring. Create the meaningful.",
  "One great prompt can save you 10 hours of manual work.",
  "The person who asks better questions gets better answers.",
  "AI is a mirror: it reflects the quality of your instructions.",
  "Skill compounds. One micro-lesson a day changes everything.",
  "The real superpower isn't AI — it's knowing how to direct it.",
];

export interface MicroLesson {
  id: string;
  title: string;
  hook: string;
  track: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  xp: number;
  tokens: number;
  visual: string;
  interaction: "tap-reveal" | "choice" | "fill-in" | "drag-drop";
  content: string;
  tryPrompt: string;
  options?: string[];
  correctAnswer?: number;
}

export const MICRO_LESSONS: MicroLesson[] = [
  // === AI BASICS (1-8) ===
  { id: "l1", title: "The 3-Part Prompt Formula", hook: "Most people write vague prompts. Here's the formula pros use.", track: "AI Basics", category: "Computer & math", difficulty: "beginner", xp: 50, tokens: 10, visual: "formula", interaction: "choice", content: "Every great prompt has 3 parts: Role + Task + Format. Example: 'You are a senior copywriter (Role). Write 3 email subject lines for a SaaS launch (Task). Keep each under 50 characters (Format).'", tryPrompt: "Try writing a prompt using Role + Task + Format for your own use case.", options: ["Role + Task + Format", "Question + Answer + Follow-up", "Topic + Length + Style", "Input + Process + Output"], correctAnswer: 0 },
  { id: "l2", title: "Spotting AI Hallucinations", hook: "AI lies confidently. Here's how to catch it every time.", track: "AI Basics", category: "Computer & math", difficulty: "beginner", xp: 60, tokens: 12, visual: "warning", interaction: "tap-reveal", content: "Hallucinations are when AI generates false information that sounds real. Red flags: specific dates without sources, invented citations, confident tone about uncertain topics. Always verify: names, dates, statistics, and legal/medical claims.", tryPrompt: "Ask AI a factual question and then verify the answer using a second source." },
  { id: "l3", title: "What AI Can't Do (Yet)", hook: "Knowing AI limits is as important as knowing its strengths.", track: "AI Basics", category: "Computer & math", difficulty: "beginner", xp: 45, tokens: 8, visual: "limits", interaction: "choice", content: "AI can't: access real-time data (unless connected), remember past conversations by default, feel emotions, or guarantee accuracy. It doesn't 'know' things — it predicts the most likely next words.", tryPrompt: "Ask AI 'What happened in the news today?' and observe the limitations.", options: ["It predicts likely next words", "It searches the internet live", "It has a real brain", "It stores all conversations"], correctAnswer: 0 },
  { id: "l4", title: "Temperature & Creativity", hook: "This one setting controls how creative AI gets.", track: "AI Basics", category: "Computer & math", difficulty: "intermediate", xp: 55, tokens: 10, visual: "slider", interaction: "choice", content: "Temperature (0-2) controls randomness. Low (0-0.3): factual, consistent, great for data/code. Medium (0.5-0.7): balanced creativity. High (0.8-1.2): wild ideas, brainstorming. Use low for accuracy, high for creative exploration.", tryPrompt: "Try generating the same prompt at temperature 0.2 and 1.0. Compare outputs.", options: ["Low = factual, High = creative", "Low = slow, High = fast", "Low = short, High = long", "Temperature doesn't matter"], correctAnswer: 0 },
  { id: "l5", title: "AI vs Search Engine", hook: "Google finds pages. AI understands context. Know when to use which.", track: "AI Basics", category: "Computer & math", difficulty: "beginner", xp: 40, tokens: 8, visual: "compare", interaction: "choice", content: "Use AI when: you need synthesis, summaries, rewriting, brainstorming, or step-by-step explanations. Use Search when: you need current events, specific URLs, live data, or verified sources.", tryPrompt: "Think of 3 tasks from your day — decide which is better for AI vs Search.", options: ["AI for synthesis, Search for live data", "Always use AI", "Always use Search", "They're the same thing"], correctAnswer: 0 },
  { id: "l6", title: "Context Windows Explained", hook: "AI forgets. Here's why and how to work around it.", track: "AI Basics", category: "Computer & math", difficulty: "intermediate", xp: 65, tokens: 12, visual: "window", interaction: "tap-reveal", content: "A context window is how much text AI can 'see' at once (e.g., 128K tokens ≈ a 300-page book). Once exceeded, it forgets earlier parts. Tips: put key info at the start and end, summarize long inputs, use chunking for documents.", tryPrompt: "Try summarizing a long article by breaking it into 3 chunks and summarizing each separately." },
  { id: "l7", title: "Fine-tuning vs Prompting", hook: "You don't always need to train a model. Prompts can do 90%.", track: "AI Basics", category: "Computer & math", difficulty: "advanced", xp: 75, tokens: 15, visual: "compare", interaction: "choice", content: "Fine-tuning = training AI on your specific data (expensive, technical). Prompt engineering = getting results through clever instructions (free, immediate). For most business tasks, well-crafted prompts outperform fine-tuning.", tryPrompt: "Write a detailed system prompt that makes AI behave like an expert in your field.", options: ["Prompting handles 90% of business tasks", "You must always fine-tune", "Prompting doesn't work well", "Fine-tuning is free"], correctAnswer: 0 },
  { id: "l8", title: "AI Safety Red Flags", hook: "These 5 signs mean you should NOT trust the AI output.", track: "AI Basics", category: "Protective service", difficulty: "beginner", xp: 50, tokens: 10, visual: "shield", interaction: "tap-reveal", content: "Never trust AI when it: 1) Cites studies you can't find, 2) Gives medical/legal advice, 3) Claims real-time data without web access, 4) Provides exact statistics without sources, 5) Says 'always' or 'never' about complex topics.", tryPrompt: "Ask AI a medical question and practice identifying which parts need professional verification." },

  // === PROMPTING & COMMUNICATION (9-16) ===
  { id: "l9", title: "Constraint Prompting", hook: "The secret to getting exactly what you want from AI.", track: "Prompting & Communication", category: "Computer & math", difficulty: "intermediate", xp: 70, tokens: 15, visual: "constraints", interaction: "choice", content: "Constraints narrow AI output. Instead of 'Write a blog post', try: 'Write a 300-word blog post for small business owners about email marketing. Use simple language. Include 3 actionable tips. No jargon.'", tryPrompt: "Add 3 constraints to a prompt you've used before and compare the outputs.", options: ["Add word count, audience, and format constraints", "Just say 'be specific'", "Write longer prompts", "Use technical language"], correctAnswer: 0 },
  { id: "l10", title: "Tone Control Mastery", hook: "Same message, completely different impact. Tone is everything.", track: "Prompting & Communication", category: "Arts & media", difficulty: "intermediate", xp: 65, tokens: 12, visual: "tone", interaction: "choice", content: "Adding tone instructions transforms output. Compare: 'Write about productivity' vs 'Write about productivity in a witty, conversational tone as if explaining to a friend over coffee.' Tone options: professional, casual, academic, empathetic, urgent, humorous.", tryPrompt: "Rewrite the same message in 3 different tones and see how the meaning shifts.", options: ["Specify the exact tone you want", "AI always picks the right tone", "Tone doesn't matter for business", "Use ALL CAPS for emphasis"], correctAnswer: 0 },
  { id: "l11", title: "Chain-of-Thought Prompting", hook: "Make AI show its work. Get better answers instantly.", track: "Prompting & Communication", category: "Computer & math", difficulty: "intermediate", xp: 70, tokens: 14, visual: "chain", interaction: "choice", content: "Adding 'Think step by step' to your prompt makes AI reason through problems instead of jumping to conclusions. Example: 'A store has 3 shelves with 8 items each. 5 items sell. How many remain? Think step by step.' AI breaks down: 3×8=24, 24-5=19.", tryPrompt: "Give AI a word problem and compare answers with and without 'think step by step'.", options: ["'Think step by step' improves reasoning", "'Be smart' works better", "AI always shows its work", "More words = worse output"], correctAnswer: 0 },
  { id: "l12", title: "Few-Shot Learning", hook: "Show AI 2-3 examples and it learns your pattern instantly.", track: "Prompting & Communication", category: "Computer & math", difficulty: "intermediate", xp: 75, tokens: 15, visual: "examples", interaction: "tap-reveal", content: "Few-shot = giving examples in your prompt. Instead of describing what you want, show it: 'Convert names to email format: John Smith → john.smith@company.com | Jane Doe → jane.doe@company.com | Now convert: Bob Johnson →'. AI matches the pattern perfectly.", tryPrompt: "Use 2-3 examples to teach AI a formatting pattern unique to your work." },
  { id: "l13", title: "Negative Prompting", hook: "Tell AI what NOT to do. It's often more effective.", track: "Prompting & Communication", category: "Computer & math", difficulty: "intermediate", xp: 60, tokens: 11, visual: "minus", interaction: "choice", content: "Negative constraints eliminate unwanted outputs. 'Write marketing copy. Do NOT use: buzzwords, exclamation marks, the word 'revolutionary', or claims we can't prove.' This prevents generic AI-sounding text.", tryPrompt: "Write a prompt with 3 positive and 3 negative constraints. See the quality difference.", options: ["'Do NOT' constraints eliminate weak output", "Negative prompts confuse AI", "Only positive instructions work", "Length matters more"], correctAnswer: 0 },
  { id: "l14", title: "System vs User Prompts", hook: "Two types of prompts. Using both = 10x better results.", track: "Prompting & Communication", category: "Computer & math", difficulty: "advanced", xp: 80, tokens: 16, visual: "layers", interaction: "tap-reveal", content: "System prompt = persistent instructions (role, rules, behavior). User prompt = the specific request. Example system: 'You are a legal contract reviewer. Always flag risks, use plain English, cite relevant clauses.' Then user: 'Review this NDA.' The system prompt shapes every response.", tryPrompt: "Write a system prompt for an AI assistant specialized in your industry." },
  { id: "l15", title: "Iterative Refinement", hook: "The first output is never the best. Here's how to iterate.", track: "Prompting & Communication", category: "Computer & math", difficulty: "intermediate", xp: 65, tokens: 12, visual: "iterate", interaction: "choice", content: "Step 1: Get initial output. Step 2: 'Make it more concise.' Step 3: 'Add specific examples for point 2.' Step 4: 'Rewrite the intro to hook a busy executive.' Each iteration improves one specific aspect.", tryPrompt: "Generate something, then refine it 3 times, improving one thing each time.", options: ["Refine one aspect per iteration", "Start over each time", "Accept the first output", "Change everything at once"], correctAnswer: 0 },
  { id: "l16", title: "Output Format Control", hook: "Tables, JSON, markdown, lists — you choose the structure.", track: "Prompting & Communication", category: "Computer & math", difficulty: "beginner", xp: 50, tokens: 9, visual: "format", interaction: "choice", content: "Always specify format: 'Format as a markdown table with columns: Task, Priority, Deadline' or 'Return as JSON with keys: title, summary, tags' or 'Use bullet points with emoji prefixes.' Structured output = immediately usable.", tryPrompt: "Ask AI for the same information in 3 different formats: table, JSON, and bullet list.", options: ["Specify exact output format", "AI chooses the best format", "Always request paragraphs", "Format doesn't affect quality"], correctAnswer: 0 },

  // === PRODUCTIVITY & BUSINESS (17-22) ===
  { id: "l17", title: "AI Email Templates", hook: "Write professional emails 10x faster with this template.", track: "Productivity & Business", category: "Office & admin", difficulty: "beginner", xp: 45, tokens: 8, visual: "template", interaction: "choice", content: "Prompt: 'Write a professional email to [recipient] about [topic]. Tone: [formal/friendly]. Include: greeting, main point in 2 sentences, clear call-to-action, sign-off.' This template works for 90% of business emails.", tryPrompt: "Use this template to draft an email you've been putting off.", options: ["Include greeting + main point + CTA", "Write everything in one paragraph", "Start with 'Dear Sir/Madam'", "Make it as long as possible"], correctAnswer: 0 },
  { id: "l18", title: "SOP Generator", hook: "Turn any process into a documented SOP in minutes.", track: "Productivity & Business", category: "Management", difficulty: "intermediate", xp: 75, tokens: 15, visual: "document", interaction: "choice", content: "Prompt: 'Create a step-by-step Standard Operating Procedure for [process]. Include: purpose, scope, required tools, numbered steps with details, common mistakes to avoid, and a checklist summary.'", tryPrompt: "Generate an SOP for a process you repeat weekly at work.", options: ["Purpose + Steps + Checklist + Mistakes", "Just list the steps", "Write it as a paragraph", "Keep it to 3 bullet points"], correctAnswer: 0 },
  { id: "l19", title: "Meeting Summary Autopilot", hook: "Never write meeting notes manually again.", track: "Productivity & Business", category: "Office & admin", difficulty: "beginner", xp: 50, tokens: 10, visual: "notes", interaction: "choice", content: "After any meeting, paste your rough notes and prompt: 'Organize into: Key Decisions, Action Items (with owners + deadlines), Open Questions, Next Steps. Format as bullet points.' AI structures chaos into clarity.", tryPrompt: "Take your last meeting's rough notes and turn them into structured action items.", options: ["Decisions + Actions + Questions + Next Steps", "Write a summary paragraph", "List everything discussed", "Only list action items"], correctAnswer: 0 },
  { id: "l20", title: "Competitive Analysis Template", hook: "Research competitors in minutes, not days.", track: "Productivity & Business", category: "Business & finance", difficulty: "intermediate", xp: 70, tokens: 14, visual: "analysis", interaction: "tap-reveal", content: "Prompt: 'Analyze [competitor]. Cover: 1) Core value proposition, 2) Target customer, 3) Pricing model, 4) Key differentiators, 5) Weaknesses/gaps, 6) What we can learn. Format as a comparison table.' Note: Verify all claims independently.", tryPrompt: "Run this analysis on your top 3 competitors. Cross-reference with their actual websites." },
  { id: "l21", title: "Content Calendar Generator", hook: "Plan 30 days of content in 5 minutes.", track: "Productivity & Business", category: "Arts & media", difficulty: "intermediate", xp: 65, tokens: 12, visual: "calendar", interaction: "choice", content: "Prompt: 'Create a 30-day content calendar for [business/niche]. Include: date, platform (LinkedIn/Twitter/Blog), topic, hook line, content type (post/thread/article), and target audience. Mix educational, entertaining, and promotional.' Always adapt to your brand voice.", tryPrompt: "Generate a content calendar for your business or personal brand for next month.", options: ["Mix educational + entertaining + promotional", "Post the same type every day", "Only promotional content", "Random topics without strategy"], correctAnswer: 0 },
  { id: "l22", title: "Customer Response Scripts", hook: "Handle any customer message professionally in seconds.", track: "Productivity & Business", category: "Sales", difficulty: "beginner", xp: 50, tokens: 10, visual: "chat", interaction: "choice", content: "Prompt: 'Write a professional customer response for: [situation]. Tone: empathetic but solution-focused. Include: acknowledgment of issue, explanation (if needed), proposed solution, and follow-up offer.' Adapt for: complaints, refund requests, feature requests, praise.", tryPrompt: "Draft responses for the 3 most common customer messages you receive.", options: ["Acknowledge + Explain + Solve + Follow-up", "Just say sorry", "Copy-paste a generic reply", "Ignore difficult messages"], correctAnswer: 0 },

  // === CREATIVITY (23-26) ===
  { id: "l23", title: "Brainstorm Multiplier", hook: "Get 10x more creative ideas with this one technique.", track: "Creativity", category: "Arts & media", difficulty: "beginner", xp: 55, tokens: 10, visual: "lightbulb", interaction: "choice", content: "Instead of 'Give me ideas for X', use: 'Give me 20 ideas for X. Make the first 10 practical and the last 10 wildly creative. Then combine the best practical idea with the best creative idea into a hybrid concept.'", tryPrompt: "Use this technique to brainstorm ideas for a project you're working on.", options: ["Ask for 20 ideas split practical/creative", "Ask for 'some ideas'", "Ask for exactly 3 ideas", "Ask for the best single idea"], correctAnswer: 0 },
  { id: "l24", title: "Storytelling Framework", hook: "Turn any boring topic into a compelling story.", track: "Creativity", category: "Arts & media", difficulty: "intermediate", xp: 65, tokens: 12, visual: "story", interaction: "tap-reveal", content: "Prompt: 'Tell the story of [topic] using this framework: 1) The Problem (create tension), 2) The Struggle (what was tried), 3) The Breakthrough (the insight), 4) The Transformation (the result). Write in a conversational, engaging tone with vivid details.'", tryPrompt: "Turn your product/service origin story into a narrative using this framework." },
  { id: "l25", title: "Visual Prompt Crafting", hook: "Describe images to AI like a photographer directs a shoot.", track: "Creativity", category: "Arts & media", difficulty: "intermediate", xp: 70, tokens: 14, visual: "camera", interaction: "choice", content: "For image AI, structure prompts as: Subject + Style + Mood + Technical specs. Example: 'A minimalist home office (subject), Scandinavian design photography (style), calm and productive mood (mood), soft natural light, shallow depth of field (technical).'", tryPrompt: "Describe 3 images you want using Subject + Style + Mood + Technical specs.", options: ["Subject + Style + Mood + Technical", "Just describe what you see", "Use one-word prompts", "Write a full paragraph"], correctAnswer: 0 },
  { id: "l26", title: "Remix & Mashup Method", hook: "Combine two unrelated ideas for breakthrough concepts.", track: "Creativity", category: "Arts & media", difficulty: "intermediate", xp: 60, tokens: 11, visual: "remix", interaction: "choice", content: "Prompt: 'Take the concept of [Thing A] and combine it with the principles of [Thing B]. Generate 5 hybrid ideas that could work as [products/content/services]. For each, explain why the combination works.'", tryPrompt: "Combine your industry with a completely unrelated field. What new ideas emerge?", options: ["Combine two unrelated concepts for hybrids", "Stay within your industry", "Copy what competitors do", "Wait for inspiration"], correctAnswer: 0 },

  // === AI FOR DAILY LIFE (27-32) ===
  { id: "l27", title: "AI Budget Planner", hook: "Create a personal budget in 60 seconds with AI.", track: "AI for Daily Life", category: "Business & finance", difficulty: "beginner", xp: 55, tokens: 10, visual: "money", interaction: "choice", content: "Prompt: 'I earn $[X]/month. My fixed expenses are [list]. Create a 50/30/20 budget breakdown with specific dollar amounts. Include 3 areas where I might be overspending.' AI can't access your bank — but it can structure your thinking.", tryPrompt: "Use AI to create your own 50/30/20 budget right now.", options: ["AI structures your financial thinking", "AI accesses your bank account", "AI predicts stock prices", "AI replaces a financial advisor"], correctAnswer: 0 },
  { id: "l28", title: "Decision Matrix Builder", hook: "Make better decisions with this AI-powered framework.", track: "AI for Daily Life", category: "Life & social sciences", difficulty: "beginner", xp: 50, tokens: 10, visual: "matrix", interaction: "tap-reveal", content: "Prompt: 'Help me decide between [Option A] and [Option B]. Create a weighted decision matrix with criteria: cost, time, risk, long-term value, effort. Score each 1-10 and calculate weighted totals. Then give your recommendation.' Works for career moves, purchases, and life decisions.", tryPrompt: "Use this matrix for a decision you've been postponing." },
  { id: "l29", title: "Meal Prep Planner", hook: "A week of meals planned in 30 seconds.", track: "AI for Daily Life", category: "Food & serving", difficulty: "beginner", xp: 40, tokens: 8, visual: "food", interaction: "choice", content: "Prompt: 'Create a 7-day meal prep plan for [dietary preference]. Budget: $[X]/week. Include: breakfast, lunch, dinner, 1 snack. Generate a consolidated grocery list organized by store section. Prioritize meals that share ingredients.'", tryPrompt: "Generate a meal plan for your actual dietary preferences and budget.", options: ["Specify diet + budget + shared ingredients", "Just say 'what should I eat'", "Only plan dinner", "Ignore budget constraints"], correctAnswer: 0 },
  { id: "l30", title: "Travel Itinerary Builder", hook: "Plan a trip like a travel agent — in 2 minutes.", track: "AI for Daily Life", category: "Transportation", difficulty: "beginner", xp: 50, tokens: 10, visual: "map", interaction: "tap-reveal", content: "Prompt: 'Plan a [X]-day trip to [destination]. Budget: [amount]. Interests: [list]. Include: daily schedule with times, transport between spots, restaurant recommendations near each attraction, one hidden gem per day, and a packing checklist.' Always verify prices and hours independently.", tryPrompt: "Plan your next weekend trip or vacation using this template." },
  { id: "l31", title: "Conflict Resolution Script", hook: "Handle tough conversations with AI-generated talking points.", track: "AI for Daily Life", category: "Social services", difficulty: "intermediate", xp: 60, tokens: 12, visual: "handshake", interaction: "choice", content: "Prompt: 'I need to have a difficult conversation about [situation]. Help me: 1) Open with empathy, 2) State my perspective using 'I' statements, 3) Ask open-ended questions, 4) Propose solutions. Tone: firm but respectful.'", tryPrompt: "Draft talking points for a conversation you've been avoiding.", options: ["Empathy + I-statements + Questions + Solutions", "Just state your demands", "Avoid the conversation entirely", "Win the argument at all costs"], correctAnswer: 0 },
  { id: "l32", title: "Study Notes Transformer", hook: "Turn messy notes into structured study material instantly.", track: "AI for Daily Life", category: "Education & library", difficulty: "beginner", xp: 45, tokens: 9, visual: "notes", interaction: "choice", content: "Prompt: 'Transform these notes into: 1) Key concepts summary (3-5 bullets), 2) Flashcard-style Q&A pairs (10 cards), 3) A one-paragraph explanation I could teach someone. Topic: [paste notes].' This triples retention.", tryPrompt: "Paste your latest class or meeting notes and transform them.", options: ["Summary + Flashcards + Teaching explanation", "Just rewrite them neatly", "Memorize raw notes", "Skip note-taking entirely"], correctAnswer: 0 },

  // === AI FOR MONEY (33-36) ===
  { id: "l33", title: "Negotiation Script Builder", hook: "AI can write your negotiation script. Here's how.", track: "AI for Money", category: "Sales", difficulty: "intermediate", xp: 70, tokens: 14, visual: "handshake", interaction: "choice", content: "Prompt: 'I need to negotiate [situation]. My position: [details]. Their likely position: [guess]. Write a negotiation script with: opening statement, 3 key arguments, 2 concession points, responses to likely objections, and a closing ask.'", tryPrompt: "Build a negotiation script for your next salary review or vendor discussion.", options: ["Arguments + Concessions + Objection handling", "Just state what you want", "Be aggressive and firm only", "Wing it and see what happens"], correctAnswer: 0 },
  { id: "l34", title: "Freelance Proposal Generator", hook: "Win more clients with AI-crafted proposals.", track: "AI for Money", category: "Business & finance", difficulty: "intermediate", xp: 70, tokens: 14, visual: "proposal", interaction: "tap-reveal", content: "Prompt: 'Write a freelance proposal for [service]. Client need: [description]. Include: understanding of their problem, my approach (3 phases), timeline, deliverables, pricing (value-based), and 2 testimonial-style proof points. Tone: confident but not salesy.'", tryPrompt: "Generate a proposal for a service you offer and customize it for a real prospect." },
  { id: "l35", title: "Subscription Audit", hook: "Find hidden money leaks in your subscriptions.", track: "AI for Money", category: "Business & finance", difficulty: "beginner", xp: 45, tokens: 9, visual: "audit", interaction: "choice", content: "Prompt: 'I have these subscriptions: [list with prices]. For each: 1) Is there a free alternative? 2) Can I negotiate a lower price? 3) Am I using it enough to justify the cost? 4) Total potential monthly savings.' Be honest about what you actually use.", tryPrompt: "List all your subscriptions and run this audit prompt right now.", options: ["Evaluate each subscription's value", "Cancel everything", "Keep all subscriptions", "Only cancel the cheapest ones"], correctAnswer: 0 },
  { id: "l36", title: "Side Hustle Finder", hook: "AI can match your skills to real income opportunities.", track: "AI for Money", category: "Business & finance", difficulty: "beginner", xp: 55, tokens: 11, visual: "rocket", interaction: "choice", content: "Prompt: 'My skills: [list]. Available time: [hours/week]. Budget to start: [amount]. Suggest 5 realistic side income ideas. For each: estimated earnings, time to first dollar, tools needed, and first 3 steps. No MLM or gambling.'", tryPrompt: "Run this prompt with your actual skills and availability.", options: ["Match skills + time + budget to real opportunities", "Look for 'get rich quick' schemes", "Only consider passive income", "Ignore skill matching"], correctAnswer: 0 },

  // === AI FOR BUSINESS (37-40) ===
  { id: "l37", title: "Review Response System", hook: "Turn negative reviews into loyal customers.", track: "AI for Business", category: "Sales", difficulty: "intermediate", xp: 65, tokens: 13, visual: "review", interaction: "choice", content: "Prompt: 'Write a response to this customer review: [paste review]. If negative: acknowledge, apologize, offer solution, invite back. If positive: thank sincerely, highlight specific point, invite to share. Keep under 100 words. Tone: genuine, not corporate.'", tryPrompt: "Respond to your last 3 customer reviews using this framework.", options: ["Acknowledge + Solve + Invite back", "Ignore negative reviews", "Use a generic response for all", "Argue with the reviewer"], correctAnswer: 0 },
  { id: "l38", title: "Sales Pipeline Messaging", hook: "Automate follow-ups that actually get responses.", track: "AI for Business", category: "Sales", difficulty: "intermediate", xp: 70, tokens: 14, visual: "pipeline", interaction: "tap-reveal", content: "Prompt: 'Create a 5-email follow-up sequence for [product/service]. Buyer stage: [awareness/consideration/decision]. Each email: subject line (under 40 chars), 3-sentence body, one CTA. Space: Day 1, Day 3, Day 7, Day 14, Day 30. Tone: helpful, not pushy.'", tryPrompt: "Generate a follow-up sequence for a prospect you're currently pursuing." },
  { id: "l39", title: "Onboarding Checklist Creator", hook: "New hire onboarding in minutes, not days.", track: "AI for Business", category: "Management", difficulty: "intermediate", xp: 60, tokens: 12, visual: "checklist", interaction: "choice", content: "Prompt: 'Create a 30-day onboarding checklist for a new [role]. Break into: Week 1 (orientation), Week 2 (training), Week 3 (shadowing), Week 4 (independence). Include: tasks, responsible person, completion criteria, and key resources.'", tryPrompt: "Generate an onboarding plan for the next role you need to fill.", options: ["4-week structured checklist with milestones", "Just give them the employee handbook", "Let them figure it out", "One-day orientation only"], correctAnswer: 0 },
  { id: "l40", title: "CRM Workflow Automator", hook: "Set up smart automations without coding.", track: "AI for Business", category: "Office & admin", difficulty: "advanced", xp: 80, tokens: 16, visual: "workflow", interaction: "tap-reveal", content: "Prompt: 'Design a CRM automation workflow for [business type]. Triggers: new lead, follow-up due, deal won, deal lost. For each trigger: action sequence, timing, message templates, and escalation rules. Include KPIs to track.' AI designs the logic; you implement in your CRM.", tryPrompt: "Map out the automation workflow for your most common sales process." },

  // === AI SURVIVAL BASICS (41-44) ===
  { id: "l41", title: "Emergency Budget Planner", hook: "Lost your income? Here's the 72-hour financial plan.", track: "AI Survival Basics", category: "Business & finance", difficulty: "beginner", xp: 55, tokens: 11, visual: "emergency", interaction: "tap-reveal", content: "Prompt: 'I need an emergency financial plan. Income: $0 for the next [X] weeks. Fixed expenses: [list]. Savings: [amount]. Help me: 1) Prioritize essential expenses, 2) List things to pause immediately, 3) Identify emergency income options, 4) Create a week-by-week survival budget.'", tryPrompt: "Run this as a hypothetical exercise with your real numbers. Knowing the plan gives you confidence." },
  { id: "l42", title: "Scam Detection Framework", hook: "AI can help you spot scams before they cost you.", track: "AI Survival Basics", category: "Protective service", difficulty: "beginner", xp: 50, tokens: 10, visual: "shield", interaction: "choice", content: "Prompt: 'Analyze this offer/message for scam indicators: [paste]. Check for: unrealistic returns, pressure tactics, vague company details, requests for personal info, too-good-to-be-true claims. Rate risk: Low/Medium/High with explanation.' Never send money or personal info based on AI analysis alone.", tryPrompt: "Paste a suspicious email or offer you received and analyze it.", options: ["Check for pressure tactics + unrealistic claims", "Trust all emails from companies", "Only worry about known scammers", "Ignore gut feelings"], correctAnswer: 0 },
  { id: "l43", title: "First Aid Info Organizer", hook: "Organize medical info for emergencies (not medical advice).", track: "AI Survival Basics", category: "Healthcare support", difficulty: "beginner", xp: 45, tokens: 9, visual: "health", interaction: "tap-reveal", content: "Prompt: 'Help me organize my household emergency medical info: allergies, medications, emergency contacts, nearest hospital, insurance info. Create a printable card format.' IMPORTANT: AI gives organizational help only — always consult medical professionals for health decisions.", tryPrompt: "Create your household emergency contact card and save it." },
  { id: "l44", title: "Home Troubleshooting Helper", hook: "Fix common home issues with step-by-step guidance.", track: "AI Survival Basics", category: "Installation & repair", difficulty: "beginner", xp: 45, tokens: 9, visual: "tools", interaction: "choice", content: "Prompt: 'My [appliance/fixture] is [problem]. Walk me through safe troubleshooting steps. Include: safety warnings first, tools needed, step-by-step diagnosis, when to call a professional. I have [skill level] DIY experience.' Always prioritize safety over DIY savings.", tryPrompt: "Describe a current home issue and get safe troubleshooting steps.", options: ["Safety first + Steps + When to call a pro", "Watch a random YouTube video", "Ignore the problem", "Try everything without precautions"], correctAnswer: 0 },
];

export const MASTERY_CATEGORIES = [
  { id: "management", name: "Management", icon: "👔" },
  { id: "business-finance", name: "Business & Finance", icon: "💰" },
  { id: "computer-math", name: "Computer & Math", icon: "💻" },
  { id: "architecture", name: "Architecture & Engineering", icon: "🏗️" },
  { id: "life-sciences", name: "Life & Social Sciences", icon: "🔬" },
  { id: "social-services", name: "Social Services", icon: "🤝" },
  { id: "legal", name: "Legal", icon: "⚖️" },
  { id: "education", name: "Education & Library", icon: "📚" },
  { id: "arts-media", name: "Arts & Media", icon: "🎨" },
  { id: "healthcare-pract", name: "Healthcare Practitioners", icon: "⚕️" },
  { id: "healthcare-support", name: "Healthcare Support", icon: "🏥" },
  { id: "protective", name: "Protective Service", icon: "🛡️" },
  { id: "food-serving", name: "Food & Serving", icon: "🍽️" },
  { id: "grounds", name: "Grounds Maintenance", icon: "🌿" },
  { id: "personal-care", name: "Personal Care", icon: "💆" },
  { id: "sales", name: "Sales", icon: "📊" },
  { id: "office-admin", name: "Office & Admin", icon: "📋" },
  { id: "agriculture", name: "Agriculture", icon: "🌾" },
  { id: "construction", name: "Construction", icon: "🔨" },
  { id: "installation", name: "Installation & Repair", icon: "🔧" },
  { id: "production", name: "Production", icon: "🏭" },
  { id: "transportation", name: "Transportation", icon: "🚛" },
];

export const TRACKS = [
  { id: "basics", name: "AI Basics", icon: "🧠", lessons: 12, completed: 3, color: "from-blue-500/20 to-blue-600/5" },
  { id: "prompting", name: "Prompting & Communication", icon: "✍️", lessons: 15, completed: 5, color: "from-primary/20 to-primary/5" },
  { id: "productivity", name: "Productivity & Business", icon: "⚡", lessons: 10, completed: 2, color: "from-amber-500/20 to-amber-600/5" },
  { id: "creativity", name: "Creativity", icon: "🎨", lessons: 8, completed: 1, color: "from-purple-500/20 to-purple-600/5" },
  { id: "daily-life", name: "AI for Daily Life", icon: "🏠", lessons: 14, completed: 0, color: "from-green-500/20 to-green-600/5" },
  { id: "money", name: "AI for Money", icon: "💵", lessons: 10, completed: 0, color: "from-emerald-500/20 to-emerald-600/5" },
  { id: "business", name: "AI for Business", icon: "🏢", lessons: 12, completed: 0, color: "from-cyan-500/20 to-cyan-600/5" },
  { id: "survival", name: "AI Survival Basics", icon: "🔥", lessons: 8, completed: 0, color: "from-orange-500/20 to-orange-600/5" },
];

export const GAMES = [
  { id: "prompt-puzzle", name: "Prompt Puzzle", description: "Drag prompt blocks into the correct order", icon: "🧩", level: 1, bestScore: 0 },
  { id: "hallucination-hunter", name: "Hallucination Hunter", description: "Spot the AI-generated false claims", icon: "🔍", level: 1, bestScore: 0 },
  { id: "output-duel", name: "Output Duel", description: "Compare outputs and pick the winner", icon: "⚔️", level: 1, bestScore: 0 },
  { id: "workflow-builder", name: "Workflow Builder", description: "Connect the workflow steps correctly", icon: "🔗", level: 1, bestScore: 0 },
  { id: "time-trial", name: "Time Trial", description: "Pick the best prompt in 60 seconds", icon: "⏱️", level: 1, bestScore: 0 },
  { id: "prompt-surgery", name: "Prompt Surgery", description: "Remove the fluff, keep the intent", icon: "✂️", level: 1, bestScore: 0 },
  { id: "context-builder", name: "Context Builder", description: "Choose which context matters most", icon: "🎯", level: 1, bestScore: 0 },
  { id: "risk-check", name: "Risk & Privacy Check", description: "Find and fix privacy issues in prompts", icon: "🛡️", level: 1, bestScore: 0 },
];

export const CATEGORY_BUNDLES = [
  { id: "business-power", name: "Business Power", categories: ["management", "business-finance", "sales", "office-admin"], tokens: 200 },
  { id: "tech-logic", name: "Tech & Logic", categories: ["computer-math", "architecture"], tokens: 150 },
  { id: "society-people", name: "Society & People", categories: ["life-sciences", "social-services", "education", "legal"], tokens: 200 },
  { id: "health-safety", name: "Health & Safety", categories: ["healthcare-pract", "healthcare-support", "protective", "personal-care"], tokens: 200 },
  { id: "hands-on", name: "Hands-On World", categories: ["construction", "installation", "production", "transportation", "agriculture", "grounds", "food-serving"], tokens: 300 },
];

export function getLevelLabel(score: number): string {
  if (score >= 90) return "Master";
  if (score >= 75) return "Architect";
  if (score >= 60) return "Strategist";
  if (score >= 40) return "Operator";
  if (score >= 20) return "Builder";
  return "Novice";
}

export function getLevelColor(score: number): string {
  if (score >= 90) return "text-gradient-gold";
  if (score >= 75) return "text-accent-red";
  if (score >= 40) return "text-foreground";
  return "text-muted-foreground";
}
