project_id = "lkzouzuvqwohkwtszmgl"

[functions.chat]
verify_jwt = false

[functions.chat-vision]
verify_jwt = false

[functions.generate-lesson]
verify_jwt = false

[functions.generate-game-question]
verify_jwt = false

[functions.generate-feed-card]
verify_jwt = false

[functions.generate-personalized-lesson]
verify_jwt = false

[functions.generate-chat-image]
verify_jwt = false
